"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
let friendNames = ["Sarmad", "Arslan", "Danish", "Hamid", "Awais", "Salman", "Mehran"];
let message = "you are my friend";
console.log(`${friendNames[0]},${message}`);
console.log(`${friendNames[1]},${message}`);
console.log(`${friendNames[2]},${message}`);
console.log(`${friendNames[3]},${message}`);
console.log(`${friendNames[4]},${message}`);
console.log(`${friendNames[5]},${message}`);
console.log(`${friendNames[6]},${message}`);
